version: '3'
services:
  php:
    container_name: ${APP_NAME}_php
    working_dir: /var/www
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ${APP_PATH}:/var/www
      - ./docker/php/conf.d/:/usr/local/etc/php/conf.d/
    networks:
      - app
    ports:
      - "9000:9000"
    depends_on:
      - db
    restart: unless-stopped

  echoserver:
    build:
      context: .
      dockerfile: ./docker/laravel-echo-server/Dockerfile
    container_name: ${APP_NAME}_echoserver
    working_dir: /usr/src/app
    depends_on:
      - redis
    networks:
      - app
    ports:
      - "6001:6001"
    restart: unless-stopped

  redis:
    image: redis
    container_name: ${APP_NAME}_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app

  yarn:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: ${APP_NAME}_yarn
    volumes:
      - ${APP_PATH}:/var/www/
    working_dir: /var/www
    networks:
      - app

  db:
    image: mysql/mysql-server
    container_name: ${APP_NAME}_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - app

  nginx:
    image: nginx
    container_name: ${APP_NAME}_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ${APP_PATH}/:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    networks:
      - app
    depends_on:
      - php

networks:
  app:
